apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonamc-deploy
  name: sonamc-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sonamc-deploy
  template:
    metadata:
      labels:
        app: sonamc-deploy
    spec:
      containers:
      - image: chophelsc19962024/sonam:19
        name: pet
